# Generated by Django 3.0.5 on 2020-05-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_link',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='note',
            name='date_time',
        ),
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
